coverage:
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 0.2
        base: auto 
        # advanced
        branches: null
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
        flags: null
        paths: null
    patch:
      default:
        # basic
        target: auto
        threshold: 0.2
        base: auto 
        # advanced
        branches: null
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
        flags: null
        paths: null
        
ignore:
  - "boml/load_data/**/*"
  - "boml/upper_iter/BOMLOuterGrad.py"
  - "boml/optimizer/BOMLOpt.py"
  - "boml/setup_model/network_utils.py"
  - "boml/setup_model/BOMLNet.py"
  - "boml/extension.py"
  
